common: &common
  product:
    version: '$(GIT:DESCRIBE-VERSION-3).$(GIT:DESCRIBE-COMMITS)'
    informationalversion: '$(VER:ALL)/$(GIT:SHORTHASH)-$(GIT:BRANCH) build $(ENV:CCNetLabel)'
    
    
# environment overrides
development: 
  <<: *common  
  build:
    config: "Debug"
    
production: 
  <<: *common
  build:
    config: "Release"
