common: &common
  product:
    version: '0.1.0.$(GIT:COMMITS)'
    informationalversion: '$(VER:ALL)-$(GIT:BRANCH) build $(ENV:CCNetLabel)'
    
    
# environment overrides
development: 
  <<: *common  
  build:
    config: "Debug"
    
production: 
  <<: *common
  build:
    config: "Release"
