common: &common
  product:
    version: '1.2.3.4'
    
    
# environment overrides
development: 
  <<: *common  
  build:
    verbose: true
    config: "Debug"
    
production: 
  <<: *common
    config: "Release"

